# Generated by Django 5.2 on 2025-04-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('specialties', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('experience', models.PositiveIntegerField()),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
