# Generated by Django 5.2 on 2025-04-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_balancetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='balance',
        ),
    ]
